set shell := ["bash", "-euo", "pipefail", "-c"]

default: ci

setup:
    python -m pip install -e ".[dev,nir]"

build:
    python -m compileall -q spikeforge_hub

test:
    pytest

lint:
    ruff check .

format:
    ruff format .

typecheck:
    @echo "No repository typecheck command is configured."

run:
    spikeforge-hub --help

clean:
    @echo "No tracked build output is generated by the source test path."

docs:
    @echo "See README.md, docs, and spikeforge_hub/CURATION.md"

ci: build lint test
